from pathlib import Path

path = Path('index.html')
html = path.read_text(encoding='utf-8')

replacements = [
    ('Stand: 27. August 2026 · Version 2026-08-27</strong>', 'Stand: 27. August 2026 · Version 2026-08-27-2</strong>'),
    ('const BUSINESS_TERMS_VERSION="2026-08-27";', 'const BUSINESS_TERMS_VERSION="2026-08-27-2";'),
    ('const BUSINESS_AVV_VERSION="2026-08-27";', 'const BUSINESS_AVV_VERSION="2026-08-27-2";'),
    ('Danach bei aktiver Buchung 29,99 € / Monat · jederzeit kündbar · keine automatische Umwandlung', 'Danach bei aktiver Buchung 29,99 € / Monat · Inhaber + bis zu 10 Mitarbeiter inklusive · jederzeit kündbar · keine automatische Umwandlung'),
    ('<p>ÜbergabeCheck Business ist eine webbasierte Software zur Organisation und Dokumentation von Wohnungsübergaben. Zum Funktionsumfang können insbesondere die Verwaltung von Objekten und Wohnungen, Übergabeprotokolle, Mängeldokumentation, Fotos, Zählerstände, digitale Unterschriften, PDF-Export, Versandfunktionen und ein Unternehmensbriefkopf gehören.</p>', '<p>ÜbergabeCheck Business ist eine webbasierte Software zur Organisation und Dokumentation von Wohnungsübergaben. Zum Funktionsumfang können insbesondere die Verwaltung von Objekten und Wohnungen, Übergabeprotokolle, Mängeldokumentation, Fotos, Zählerstände, digitale Unterschriften, PDF-Export, Versandfunktionen, ein Unternehmensbriefkopf sowie eine rollenbasierte Teamverwaltung gehören. Das Unternehmenskonto unterscheidet die Rollen Inhaber, Admin und Mitarbeiter mit unterschiedlichen Berechtigungen.</p>'),
    ('<p>Der Business-Tarif kostet derzeit 29,99 € pro Monat. Maßgeblich ist der im Buchungsprozess ausgewiesene Preis. Solange die Umsätze des Anbieters unter die Steuerbefreiung für Kleinunternehmer nach § 19 UStG fallen, wird keine Umsatzsteuer berechnet; die Rechnung enthält einen entsprechenden Hinweis auf die Steuerbefreiung.</p>', '<p>Der Business-Tarif kostet derzeit 29,99 € pro Monat. Maßgeblich ist der im Buchungsprozess ausgewiesene Preis. Im Tarif enthalten sind ein Inhaberzugang sowie bis zu 10 zusätzliche Mitarbeiterzugänge für dasselbe Unternehmen. Für diese enthaltenen Teamzugänge wird kein separates Abonnement je Mitarbeiter abgeschlossen. Weitere Nutzerkontingente über diese Grenze hinaus sind nicht Bestandteil des Standardtarifs, sofern sie nicht gesondert angeboten oder vereinbart werden. Solange die Umsätze des Anbieters unter die Steuerbefreiung für Kleinunternehmer nach § 19 UStG fallen, wird keine Umsatzsteuer berechnet; die Rechnung enthält einen entsprechenden Hinweis auf die Steuerbefreiung.</p>'),
    ('<ul><li>Der Kunde hält seine Konto- und Unternehmensdaten aktuell und schützt seine Zugangsdaten vor unbefugtem Zugriff.</li><li>Der Kunde stellt sicher, dass er personenbezogene Daten, Fotos, Unterschriften und sonstige Inhalte rechtmäßig in ÜbergabeCheck Business verarbeiten darf.</li><li>Der Kunde ist für die Information betroffener Personen und die Erfüllung eigener datenschutzrechtlicher Pflichten verantwortlich.</li><li>Besondere Kategorien personenbezogener Daten im Sinne des Art. 9 DSGVO sind nicht für die reguläre Nutzung vorgesehen. Soweit der Kunde solche Daten dennoch verarbeitet, ist er für eine tragfähige Rechtsgrundlage, Datenminimierung und erforderliche Schutzmaßnahmen verantwortlich.</li><li>Rechtswidrige Inhalte, Schadsoftware sowie eine missbräuchliche oder sicherheitsgefährdende Nutzung sind untersagt.</li></ul>', '<ul><li>Der Kunde hält seine Konto- und Unternehmensdaten aktuell und schützt seine Zugangsdaten vor unbefugtem Zugriff.</li><li>Jede berechtigte Person nutzt einen eigenen Benutzerzugang. Das Teilen gemeinsamer Zugangsdaten zwischen mehreren Personen ist nicht vorgesehen.</li><li>Der Inhaber bzw. hierzu berechtigte Admins vergeben Rollen nach dem Erforderlichkeitsprinzip und entfernen Zugänge unverzüglich, wenn Mitarbeiter das Unternehmen verlassen oder keinen Zugriff mehr benötigen.</li><li>Der Kunde stellt sicher, dass er personenbezogene Daten, Fotos, Unterschriften und sonstige Inhalte rechtmäßig in ÜbergabeCheck Business verarbeiten darf.</li><li>Der Kunde ist für die Information betroffener Personen und die Erfüllung eigener datenschutzrechtlicher Pflichten verantwortlich.</li><li>Besondere Kategorien personenbezogener Daten im Sinne des Art. 9 DSGVO sind nicht für die reguläre Nutzung vorgesehen. Soweit der Kunde solche Daten dennoch verarbeitet, ist er für eine tragfähige Rechtsgrundlage, Datenminimierung und erforderliche Schutzmaßnahmen verantwortlich.</li><li>Rechtswidrige Inhalte, Schadsoftware sowie eine missbräuchliche oder sicherheitsgefährdende Nutzung sind untersagt.</li></ul>'),
    ('<p>Der Kunde bestimmt Zwecke und Mittel seiner fachlichen Verarbeitung und ist für deren Rechtmäßigkeit verantwortlich. Die Nutzung der in der Anwendung vorgesehenen Funktionen gilt als dokumentierte Weisung. Zusätzliche Weisungen können in Textform an info@uebergabe-check.de erteilt werden. Hält ÜbergabeCheck eine Weisung für datenschutzwidrig, wird der Kunde hierauf hingewiesen und die Ausführung darf bis zur Klärung ausgesetzt werden.</p>', '<p>Der Kunde bestimmt Zwecke und Mittel seiner fachlichen Verarbeitung und ist für deren Rechtmäßigkeit verantwortlich. Die Nutzung der in der Anwendung vorgesehenen Funktionen gilt als dokumentierte Weisung. Der Kunde steuert, welche eigenen Mitarbeiter über persönliche Benutzerkonten Zugriff erhalten, weist ihnen geeignete Rollen zu und stellt sicher, dass nur erforderliche und entsprechend verpflichtete Personen auf personenbezogene Inhaltsdaten zugreifen. Zusätzliche Weisungen können in Textform an info@uebergabe-check.de erteilt werden. Hält ÜbergabeCheck eine Weisung für datenschutzwidrig, wird der Kunde hierauf hingewiesen und die Ausführung darf bis zur Klärung ausgesetzt werden.</p>'),
]

for old, new in replacements:
    if old not in html:
        raise SystemExit(f'Expected pattern missing: {old[:90]}')
    html = html.replace(old, new)

path.write_text(html, encoding='utf-8')
print('Applied Business team tariff and legal version 2026-08-27-2')
